volumes:
  event_manager_db: {}

services:
  db:
    image: postgres:16-alpine
    container_name: event_manager_db
    env_file:
      - ./.env
    volumes:
      - event_manager_db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: elestio/pgadmin:REL-8_13
    container_name: event_manager_pgAdmin
    env_file:
      - ./.env
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/storage:/var/lib/pgadmin/storage

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: event_manager_local_mailpit
    ports:
      - "8025:8025"
